//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.02 at 06:18:36 PM CET 
//


package employmentpo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the employment.po package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: employment.po
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Records }
     * 
     */
    public Records createRecords() {
        return new Records();
    }

    /**
     * Create an instance of {@link Records.Record }
     * 
     */
    public Records.Record createRecordsRecord() {
        return new Records.Record();
    }

    /**
     * Create an instance of {@link Records.Record.EmploymentRecord }
     * 
     */
    public Records.Record.EmploymentRecord createRecordsRecordEmploymentRecord() {
        return new Records.Record.EmploymentRecord();
    }

    /**
     * Create an instance of {@link ExtendedInformationType }
     * 
     */
    public ExtendedInformationType createExtendedInformationType() {
        return new ExtendedInformationType();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link ContactInfoType }
     * 
     */
    public ContactInfoType createContactInfoType() {
        return new ContactInfoType();
    }

    /**
     * Create an instance of {@link CompanyInfoType }
     * 
     */
    public CompanyInfoType createCompanyInfoType() {
        return new CompanyInfoType();
    }

    /**
     * Create an instance of {@link ExtendedPositionInfoType }
     * 
     */
    public ExtendedPositionInfoType createExtendedPositionInfoType() {
        return new ExtendedPositionInfoType();
    }

    /**
     * Create an instance of {@link PositionInfoType }
     * 
     */
    public PositionInfoType createPositionInfoType() {
        return new PositionInfoType();
    }

    /**
     * Create an instance of {@link AllLocationType }
     * 
     */
    public AllLocationType createAllLocationType() {
        return new AllLocationType();
    }

    /**
     * Create an instance of {@link CompanyLocationType }
     * 
     */
    public CompanyLocationType createCompanyLocationType() {
        return new CompanyLocationType();
    }

    /**
     * Create an instance of {@link ContactInformationType }
     * 
     */
    public ContactInformationType createContactInformationType() {
        return new ContactInformationType();
    }

    /**
     * Create an instance of {@link BasicInformationType }
     * 
     */
    public BasicInformationType createBasicInformationType() {
        return new BasicInformationType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link Records.Record.EmploymentRecord.CompanyInfo }
     * 
     */
    public Records.Record.EmploymentRecord.CompanyInfo createRecordsRecordEmploymentRecordCompanyInfo() {
        return new Records.Record.EmploymentRecord.CompanyInfo();
    }

    /**
     * Create an instance of {@link Records.Record.EmploymentRecord.Positions }
     * 
     */
    public Records.Record.EmploymentRecord.Positions createRecordsRecordEmploymentRecordPositions() {
        return new Records.Record.EmploymentRecord.Positions();
    }

}
