//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.02 at 06:18:36 PM CET 
//


package employment.po;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="record" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="employmentRecord" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="companyInfo">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="contactInfo" type="{http://xml.netbeans.org/schema/commonSchema}contactInformationType"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="startDate" type="{http://xml.netbeans.org/schema/commonSchema}minBoundedDate"/>
 *                             &lt;element name="endDate" type="{http://xml.netbeans.org/schema/commonSchema}minBoundedDate"/>
 *                             &lt;element name="positions">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="position" type="{http://xml.netbeans.org/schema/commonSchema}extendedPositionInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="personalNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "record"
})
@XmlRootElement(name = "records", namespace = "http://xml.netbeans.org/schema/employmentRecordXmlSchema")
public class Records {

    @XmlElement(namespace = "http://xml.netbeans.org/schema/employmentRecordXmlSchema", required = true)
    protected List<Records.Record> record;

    /**
     * Gets the value of the record property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the record property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Records.Record }
     * 
     * 
     */
    public List<Records.Record> getRecord() {
        if (record == null) {
            record = new ArrayList<Records.Record>();
        }
        return this.record;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="employmentRecord" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="companyInfo">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="contactInfo" type="{http://xml.netbeans.org/schema/commonSchema}contactInformationType"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="startDate" type="{http://xml.netbeans.org/schema/commonSchema}minBoundedDate"/>
     *                   &lt;element name="endDate" type="{http://xml.netbeans.org/schema/commonSchema}minBoundedDate"/>
     *                   &lt;element name="positions">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="position" type="{http://xml.netbeans.org/schema/commonSchema}extendedPositionInfoType" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="personalNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "employmentRecord"
    })
    public static class Record {

        @XmlElement(namespace = "http://xml.netbeans.org/schema/employmentRecordXmlSchema", required = true)
        protected List<Records.Record.EmploymentRecord> employmentRecord;
        @XmlAttribute(name = "personalNumber")
        protected String personalNumber;

        /**
         * Gets the value of the employmentRecord property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the employmentRecord property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEmploymentRecord().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Records.Record.EmploymentRecord }
         * 
         * 
         */
        public List<Records.Record.EmploymentRecord> getEmploymentRecord() {
            if (employmentRecord == null) {
                employmentRecord = new ArrayList<Records.Record.EmploymentRecord>();
            }
            return this.employmentRecord;
        }

        /**
         * Gets the value of the personalNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonalNumber() {
            return personalNumber;
        }

        /**
         * Sets the value of the personalNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonalNumber(String value) {
            this.personalNumber = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="companyInfo">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="contactInfo" type="{http://xml.netbeans.org/schema/commonSchema}contactInformationType"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="startDate" type="{http://xml.netbeans.org/schema/commonSchema}minBoundedDate"/>
         *         &lt;element name="endDate" type="{http://xml.netbeans.org/schema/commonSchema}minBoundedDate"/>
         *         &lt;element name="positions">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="position" type="{http://xml.netbeans.org/schema/commonSchema}extendedPositionInfoType" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "companyInfo",
            "startDate",
            "endDate",
            "positions"
        })
        public static class EmploymentRecord {

            @XmlElement(namespace = "http://xml.netbeans.org/schema/employmentRecordXmlSchema", required = true)
            protected Records.Record.EmploymentRecord.CompanyInfo companyInfo;
            @XmlElement(namespace = "http://xml.netbeans.org/schema/employmentRecordXmlSchema", required = true)
            protected XMLGregorianCalendar startDate;
            @XmlElement(namespace = "http://xml.netbeans.org/schema/employmentRecordXmlSchema", required = true)
            protected XMLGregorianCalendar endDate;
            @XmlElement(namespace = "http://xml.netbeans.org/schema/employmentRecordXmlSchema", required = true)
            protected Records.Record.EmploymentRecord.Positions positions;

            /**
             * Gets the value of the companyInfo property.
             * 
             * @return
             *     possible object is
             *     {@link Records.Record.EmploymentRecord.CompanyInfo }
             *     
             */
            public Records.Record.EmploymentRecord.CompanyInfo getCompanyInfo() {
                return companyInfo;
            }

            /**
             * Sets the value of the companyInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link Records.Record.EmploymentRecord.CompanyInfo }
             *     
             */
            public void setCompanyInfo(Records.Record.EmploymentRecord.CompanyInfo value) {
                this.companyInfo = value;
            }

            /**
             * Gets the value of the startDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getStartDate() {
                return startDate;
            }

            /**
             * Sets the value of the startDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setStartDate(XMLGregorianCalendar value) {
                this.startDate = value;
            }

            /**
             * Gets the value of the endDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getEndDate() {
                return endDate;
            }

            /**
             * Sets the value of the endDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setEndDate(XMLGregorianCalendar value) {
                this.endDate = value;
            }

            /**
             * Gets the value of the positions property.
             * 
             * @return
             *     possible object is
             *     {@link Records.Record.EmploymentRecord.Positions }
             *     
             */
            public Records.Record.EmploymentRecord.Positions getPositions() {
                return positions;
            }

            /**
             * Sets the value of the positions property.
             * 
             * @param value
             *     allowed object is
             *     {@link Records.Record.EmploymentRecord.Positions }
             *     
             */
            public void setPositions(Records.Record.EmploymentRecord.Positions value) {
                this.positions = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="contactInfo" type="{http://xml.netbeans.org/schema/commonSchema}contactInformationType"/>
             *       &lt;/sequence>
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "contactInfo"
            })
            public static class CompanyInfo {

                @XmlElement(namespace = "http://xml.netbeans.org/schema/employmentRecordXmlSchema", required = true)
                protected ContactInformationType contactInfo;
                @XmlAttribute(name = "name")
                @XmlSchemaType(name = "anySimpleType")
                protected String name;

                /**
                 * Gets the value of the contactInfo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ContactInformationType }
                 *     
                 */
                public ContactInformationType getContactInfo() {
                    return contactInfo;
                }

                /**
                 * Sets the value of the contactInfo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ContactInformationType }
                 *     
                 */
                public void setContactInfo(ContactInformationType value) {
                    this.contactInfo = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="position" type="{http://xml.netbeans.org/schema/commonSchema}extendedPositionInfoType" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "position"
            })
            public static class Positions {

                @XmlElement(namespace = "http://xml.netbeans.org/schema/employmentRecordXmlSchema")
                protected List<ExtendedPositionInfoType> position;

                /**
                 * Gets the value of the position property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the position property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getPosition().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ExtendedPositionInfoType }
                 * 
                 * 
                 */
                public List<ExtendedPositionInfoType> getPosition() {
                    if (position == null) {
                        position = new ArrayList<ExtendedPositionInfoType>();
                    }
                    return this.position;
                }

            }

        }

    }

}
