
package companies.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CompaniesService", targetNamespace = "http://companies.service/companies")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CompaniesService {


    /**
     * 
     * @return
     *     returns companies.client.GetCompaniesResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompanies", targetNamespace = "http://companies.service/companies", className = "companies.client.GetCompanies")
    @ResponseWrapper(localName = "getCompaniesResponse", targetNamespace = "http://companies.service/companies", className = "companies.client.GetCompaniesResponse")
    @Action(input = "http://companies.service/companies/CompaniesService/getCompaniesRequest", output = "http://companies.service/companies/CompaniesService/getCompaniesResponse")
    public companies.client.GetCompaniesResponse.Return getCompanies();

}
