/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HangmanClientUI.java
 *
 * Created on Nov 2, 2011, 8:49:48 PM
 */
package client;

import java.awt.Component;

/**
 *
 * @author Igor
 */
public class HangmanClientUI extends javax.swing.JFrame {
    /** Creates new form HangmanClientUI */
    public HangmanClientUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        imageLabel = new javax.swing.JLabel();
        scoresPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        attemptsLeftField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        totalScoreField = new javax.swing.JTextField();
        gamePanel = new javax.swing.JPanel();
        aButton = new javax.swing.JButton();
        bButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        dButton = new javax.swing.JButton();
        eButton = new javax.swing.JButton();
        fButton = new javax.swing.JButton();
        gButton = new javax.swing.JButton();
        hButton = new javax.swing.JButton();
        iButton = new javax.swing.JButton();
        jButton = new javax.swing.JButton();
        kButton = new javax.swing.JButton();
        lButton = new javax.swing.JButton();
        mButton = new javax.swing.JButton();
        nButton = new javax.swing.JButton();
        oButton = new javax.swing.JButton();
        pButton = new javax.swing.JButton();
        qButton = new javax.swing.JButton();
        rButton = new javax.swing.JButton();
        sButton = new javax.swing.JButton();
        tButton = new javax.swing.JButton();
        uButton = new javax.swing.JButton();
        vButton = new javax.swing.JButton();
        wButton = new javax.swing.JButton();
        xButton = new javax.swing.JButton();
        yButton = new javax.swing.JButton();
        zButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        gameMenu = new javax.swing.JMenu();
        newGameMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        connectMenuItem = new javax.swing.JMenuItem();
        disconnectMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hangman");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setIcon(new javax.swing.ImageIcon("D:\\Programming\\NetBeansProjects\\ID2212_HW1\\data\\img\\0.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(imageLabel, gridBagConstraints);

        scoresPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Score"));
        scoresPanel.setLayout(new java.awt.GridLayout(2, 2, 1, 1));

        jLabel2.setText("Attempts left:");
        scoresPanel.add(jLabel2);
        scoresPanel.add(attemptsLeftField);

        jLabel1.setText("Total Score:");
        scoresPanel.add(jLabel1);
        scoresPanel.add(totalScoreField);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(scoresPanel, gridBagConstraints);

        gamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Keyboard"));
        gamePanel.setLayout(new java.awt.GridLayout(2, 0));

        aButton.setText("A");
        aButton.addActionListener(letterListener);
        gamePanel.add(aButton);

        bButton.setText("B");
        bButton.addActionListener(letterListener);
        gamePanel.add(bButton);

        cButton.setText("C");
        cButton.addActionListener(letterListener);
        gamePanel.add(cButton);

        dButton.setText("D");
        dButton.addActionListener(letterListener);
        gamePanel.add(dButton);

        eButton.setText("E");
        eButton.addActionListener(letterListener);
        gamePanel.add(eButton);

        fButton.setText("F");
        fButton.addActionListener(letterListener);
        gamePanel.add(fButton);

        gButton.setText("G");
        gButton.addActionListener(letterListener);
        gamePanel.add(gButton);

        hButton.setText("H");
        hButton.addActionListener(letterListener);
        gamePanel.add(hButton);

        iButton.setText("I");
        iButton.addActionListener(letterListener);
        gamePanel.add(iButton);

        jButton.setText("J");
        jButton.addActionListener(letterListener);
        gamePanel.add(jButton);

        kButton.setText("K");
        kButton.addActionListener(letterListener);
        gamePanel.add(kButton);

        lButton.setText("L");
        lButton.addActionListener(letterListener);
        gamePanel.add(lButton);

        mButton.setText("M");
        mButton.addActionListener(letterListener);
        gamePanel.add(mButton);

        nButton.setText("N");
        nButton.addActionListener(letterListener);
        gamePanel.add(nButton);

        oButton.setText("O");
        oButton.addActionListener(letterListener);
        gamePanel.add(oButton);

        pButton.setText("P");
        pButton.addActionListener(letterListener);
        gamePanel.add(pButton);

        qButton.setText("Q");
        qButton.addActionListener(letterListener);
        gamePanel.add(qButton);

        rButton.setText("R");
        rButton.addActionListener(letterListener);
        gamePanel.add(rButton);

        sButton.setText("S");
        sButton.addActionListener(letterListener);
        gamePanel.add(sButton);

        tButton.setText("T");
        tButton.addActionListener(letterListener);
        gamePanel.add(tButton);

        uButton.setText("U");
        uButton.addActionListener(letterListener);
        gamePanel.add(uButton);

        vButton.setText("V");
        vButton.addActionListener(letterListener);
        gamePanel.add(vButton);

        wButton.setText("W");
        wButton.addActionListener(letterListener);
        gamePanel.add(wButton);

        xButton.setText("X");
        xButton.addActionListener(letterListener);
        gamePanel.add(xButton);

        yButton.setText("Y");
        yButton.addActionListener(letterListener);
        gamePanel.add(yButton);

        zButton.setText("Z");
        zButton.addActionListener(letterListener);
        gamePanel.add(zButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(gamePanel, gridBagConstraints);

        gameMenu.setText("Game");

        newGameMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        newGameMenuItem.setText("New Game");
        gameMenu.add(newGameMenuItem);
        gameMenu.add(jSeparator2);

        connectMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        connectMenuItem.setText("Connect...");
        gameMenu.add(connectMenuItem);

        disconnectMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        disconnectMenuItem.setText("Disconnect");
        gameMenu.add(disconnectMenuItem);
        gameMenu.add(jSeparator1);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        exitMenuItem.setText("Exit");
        gameMenu.add(exitMenuItem);

        menuBar.add(gameMenu);

        setJMenuBar(menuBar);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-724)/2, (screenSize.height-450)/2, 724, 450);
    }// </editor-fold>//GEN-END:initComponents
    java.awt.event.ActionListener letterListener = new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            javax.swing.JButton button = (javax.swing.JButton) evt.getSource();
            char letter = button.getText().charAt(0);
            System.out.println(letter);
            button.setEnabled(false);
        }
    };

    private void prepareNewGame() {
        //enable all letters
        for (java.awt.Component c : gamePanel.getComponents()) {
            c.setEnabled(true);
            //System.out.println(((javax.swing.JButton) c).getText());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HangmanClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HangmanClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HangmanClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HangmanClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HangmanClientUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aButton;
    private javax.swing.JTextField attemptsLeftField;
    private javax.swing.JButton bButton;
    private javax.swing.JButton cButton;
    private javax.swing.JMenuItem connectMenuItem;
    private javax.swing.JButton dButton;
    private javax.swing.JMenuItem disconnectMenuItem;
    private javax.swing.JButton eButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JButton fButton;
    private javax.swing.JButton gButton;
    private javax.swing.JMenu gameMenu;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JButton hButton;
    private javax.swing.JButton iButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JButton kButton;
    private javax.swing.JButton lButton;
    private javax.swing.JButton mButton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton nButton;
    private javax.swing.JMenuItem newGameMenuItem;
    private javax.swing.JButton oButton;
    private javax.swing.JButton pButton;
    private javax.swing.JButton qButton;
    private javax.swing.JButton rButton;
    private javax.swing.JButton sButton;
    private javax.swing.JPanel scoresPanel;
    private javax.swing.JButton tButton;
    private javax.swing.JTextField totalScoreField;
    private javax.swing.JButton uButton;
    private javax.swing.JButton vButton;
    private javax.swing.JButton wButton;
    private javax.swing.JButton xButton;
    private javax.swing.JButton yButton;
    private javax.swing.JButton zButton;
    // End of variables declaration//GEN-END:variables
}
