
package university.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b04 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UniversityWS", targetNamespace = "http://university.service/university", wsdlLocation = "http://localhost:8080/TempWSP_HW2/UniversityWS?wsdl")
public class UniversityWS_Service
    extends Service
{

    private final static URL UNIVERSITYWS_WSDL_LOCATION;
    private final static WebServiceException UNIVERSITYWS_EXCEPTION;
    private final static QName UNIVERSITYWS_QNAME = new QName("http://university.service/university", "UniversityWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TempWSP_HW2/UniversityWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UNIVERSITYWS_WSDL_LOCATION = url;
        UNIVERSITYWS_EXCEPTION = e;
    }

    public UniversityWS_Service() {
        super(__getWsdlLocation(), UNIVERSITYWS_QNAME);
    }

    public UniversityWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), UNIVERSITYWS_QNAME, features);
    }

    public UniversityWS_Service(URL wsdlLocation) {
        super(wsdlLocation, UNIVERSITYWS_QNAME);
    }

    public UniversityWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UNIVERSITYWS_QNAME, features);
    }

    public UniversityWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UniversityWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UniversityWS
     */
    @WebEndpoint(name = "UniversityWebServicePort")
    public UniversityWS getUniversityWebServicePort() {
        return super.getPort(new QName("http://university.service/university", "UniversityWebServicePort"), UniversityWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UniversityWS
     */
    @WebEndpoint(name = "UniversityWebServicePort")
    public UniversityWS getUniversityWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://university.service/university", "UniversityWebServicePort"), UniversityWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UNIVERSITYWS_EXCEPTION!= null) {
            throw UNIVERSITYWS_EXCEPTION;
        }
        return UNIVERSITYWS_WSDL_LOCATION;
    }

}
