
package university.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b04 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UniversityWS", targetNamespace = "http://university.service/university")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UniversityWS {


    /**
     * 
     * @param personalNumber
     * @return
     *     returns university.service.client.RetrieveTranscriptResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveTranscript", targetNamespace = "http://university.service/university", className = "university.service.client.RetrieveTranscript")
    @ResponseWrapper(localName = "retrieveTranscriptResponse", targetNamespace = "http://university.service/university", className = "university.service.client.RetrieveTranscriptResponse")
    @Action(input = "http://university.service/university/UniversityWS/retrieveTranscriptRequest", output = "http://university.service/university/UniversityWS/retrieveTranscriptResponse")
    public university.service.client.RetrieveTranscriptResponse.Return retrieveTranscript(
        @WebParam(name = "personalNumber", targetNamespace = "")
        String personalNumber);

}
