//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.03 at 06:07:35 PM CET 
//


package com.myprofile.profile;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProfileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProfileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Age">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *               &lt;minExclusive value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MotivationOfVisit">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="all"/>
 *               &lt;enumeration value="adventure"/>
 *               &lt;enumeration value="art of culture"/>
 *               &lt;enumeration value="educational"/>
 *               &lt;enumeration value="welfare and relaxing"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Education">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="higher education "/>
 *               &lt;enumeration value="postsecondary education"/>
 *               &lt;enumeration value="elementary education"/>
 *               &lt;enumeration value="secondary education"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Attitude">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="greedy"/>
 *               &lt;enumeration value="normal"/>
 *               &lt;enumeration value="conservative"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Privacy">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *               &lt;minExclusive value="0"/>
 *               &lt;maxExclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VisitedItems">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="VisitedItem" type="{http://www.MyProfile.com/Profile}MuseumItem" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Interests">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Interest" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProfileType", propOrder = {
    "age",
    "motivationOfVisit",
    "education",
    "attitude",
    "privacy",
    "visitedItems",
    "interests"
})
public class ProfileType {

    @XmlElement(name = "Age")
    protected long age;
    @XmlElement(name = "MotivationOfVisit", required = true)
    protected String motivationOfVisit;
    @XmlElement(name = "Education", required = true)
    protected String education;
    @XmlElement(name = "Attitude", required = true)
    protected String attitude;
    @XmlElement(name = "Privacy")
    protected double privacy;
    @XmlElement(name = "VisitedItems", required = true)
    protected ProfileType.VisitedItems visitedItems;
    @XmlElement(name = "Interests", required = true)
    protected ProfileType.Interests interests;

    /**
     * Gets the value of the age property.
     * 
     */
    public long getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     */
    public void setAge(long value) {
        this.age = value;
    }

    /**
     * Gets the value of the motivationOfVisit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotivationOfVisit() {
        return motivationOfVisit;
    }

    /**
     * Sets the value of the motivationOfVisit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotivationOfVisit(String value) {
        this.motivationOfVisit = value;
    }

    /**
     * Gets the value of the education property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEducation() {
        return education;
    }

    /**
     * Sets the value of the education property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEducation(String value) {
        this.education = value;
    }

    /**
     * Gets the value of the attitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttitude() {
        return attitude;
    }

    /**
     * Sets the value of the attitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttitude(String value) {
        this.attitude = value;
    }

    /**
     * Gets the value of the privacy property.
     * 
     */
    public double getPrivacy() {
        return privacy;
    }

    /**
     * Sets the value of the privacy property.
     * 
     */
    public void setPrivacy(double value) {
        this.privacy = value;
    }

    /**
     * Gets the value of the visitedItems property.
     * 
     * @return
     *     possible object is
     *     {@link ProfileType.VisitedItems }
     *     
     */
    public ProfileType.VisitedItems getVisitedItems() {
        return visitedItems;
    }

    /**
     * Sets the value of the visitedItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfileType.VisitedItems }
     *     
     */
    public void setVisitedItems(ProfileType.VisitedItems value) {
        this.visitedItems = value;
    }

    /**
     * Gets the value of the interests property.
     * 
     * @return
     *     possible object is
     *     {@link ProfileType.Interests }
     *     
     */
    public ProfileType.Interests getInterests() {
        return interests;
    }

    /**
     * Sets the value of the interests property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfileType.Interests }
     *     
     */
    public void setInterests(ProfileType.Interests value) {
        this.interests = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Interest" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "interest"
    })
    public static class Interests {

        @XmlElement(name = "Interest", required = true)
        protected List<String> interest;

        /**
         * Gets the value of the interest property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the interest property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInterest().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getInterest() {
            if (interest == null) {
                interest = new ArrayList<String>();
            }
            return this.interest;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="VisitedItem" type="{http://www.MyProfile.com/Profile}MuseumItem" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "visitedItem"
    })
    public static class VisitedItems {

        @XmlElement(name = "VisitedItem")
        protected List<MuseumItem> visitedItem;

        /**
         * Gets the value of the visitedItem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the visitedItem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVisitedItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MuseumItem }
         * 
         * 
         */
        public List<MuseumItem> getVisitedItem() {
            if (visitedItem == null) {
                visitedItem = new ArrayList<MuseumItem>();
            }
            return this.visitedItem;
        }

    }

}
