
package employment.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmploymentService", targetNamespace = "http://employment.service/employment", wsdlLocation = "http://localhost:8080/HW2_BETA/employment?wsdl")
public class EmploymentService_Service
    extends Service
{

    private final static URL EMPLOYMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYMENTSERVICE_EXCEPTION;
    private final static QName EMPLOYMENTSERVICE_QNAME = new QName("http://employment.service/employment", "EmploymentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/HW2_BETA/employment?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYMENTSERVICE_WSDL_LOCATION = url;
        EMPLOYMENTSERVICE_EXCEPTION = e;
    }

    public EmploymentService_Service() {
        super(__getWsdlLocation(), EMPLOYMENTSERVICE_QNAME);
    }

    public EmploymentService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYMENTSERVICE_QNAME, features);
    }

    public EmploymentService_Service(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYMENTSERVICE_QNAME);
    }

    public EmploymentService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYMENTSERVICE_QNAME, features);
    }

    public EmploymentService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmploymentService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmploymentService
     */
    @WebEndpoint(name = "EmploymentWebServicePort")
    public EmploymentService getEmploymentWebServicePort() {
        return super.getPort(new QName("http://employment.service/employment", "EmploymentWebServicePort"), EmploymentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmploymentService
     */
    @WebEndpoint(name = "EmploymentWebServicePort")
    public EmploymentService getEmploymentWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://employment.service/employment", "EmploymentWebServicePort"), EmploymentService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYMENTSERVICE_EXCEPTION!= null) {
            throw EMPLOYMENTSERVICE_EXCEPTION;
        }
        return EMPLOYMENTSERVICE_WSDL_LOCATION;
    }

}
