
package companies.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CompaniesService", targetNamespace = "http://companies.service/companies", wsdlLocation = "http://localhost:8081/HW2_BETA/companies?wsdl")
public class CompaniesService_Service
    extends Service
{

    private final static URL COMPANIESSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMPANIESSERVICE_EXCEPTION;
    private final static QName COMPANIESSERVICE_QNAME = new QName("http://companies.service/companies", "CompaniesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/HW2_BETA/companies?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMPANIESSERVICE_WSDL_LOCATION = url;
        COMPANIESSERVICE_EXCEPTION = e;
    }

    public CompaniesService_Service() {
        super(__getWsdlLocation(), COMPANIESSERVICE_QNAME);
    }

    public CompaniesService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPANIESSERVICE_QNAME, features);
    }

    public CompaniesService_Service(URL wsdlLocation) {
        super(wsdlLocation, COMPANIESSERVICE_QNAME);
    }

    public CompaniesService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPANIESSERVICE_QNAME, features);
    }

    public CompaniesService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompaniesService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CompaniesService
     */
    @WebEndpoint(name = "CompaniesWebServicePort")
    public CompaniesService getCompaniesWebServicePort() {
        return super.getPort(new QName("http://companies.service/companies", "CompaniesWebServicePort"), CompaniesService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CompaniesService
     */
    @WebEndpoint(name = "CompaniesWebServicePort")
    public CompaniesService getCompaniesWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://companies.service/companies", "CompaniesWebServicePort"), CompaniesService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPANIESSERVICE_EXCEPTION!= null) {
            throw COMPANIESSERVICE_EXCEPTION;
        }
        return COMPANIESSERVICE_WSDL_LOCATION;
    }

}
