//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.03 at 06:07:35 PM CET 
//


package com.myprofile.profile;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.myprofile.profile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UserProfile_QNAME = new QName("http://www.MyProfile.com/Profile", "UserProfile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.myprofile.profile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProfileType }
     * 
     */
    public ProfileType createProfileType() {
        return new ProfileType();
    }

    /**
     * Create an instance of {@link ProfileType.Interests }
     * 
     */
    public ProfileType.Interests createProfileTypeInterests() {
        return new ProfileType.Interests();
    }

    /**
     * Create an instance of {@link ProfileType.VisitedItems }
     * 
     */
    public ProfileType.VisitedItems createProfileTypeVisitedItems() {
        return new ProfileType.VisitedItems();
    }

    /**
     * Create an instance of {@link MuseumItem }
     * 
     */
    public MuseumItem createMuseumItem() {
        return new MuseumItem();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProfileType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.MyProfile.com/Profile", name = "UserProfile")
    public JAXBElement<ProfileType> createUserProfile(ProfileType value) {
        return new JAXBElement<ProfileType>(_UserProfile_QNAME, ProfileType.class, null, value);
    }

}
